server:
  port: 8084

environment: General Environment

spring:
  profiles:
    active: dev
  application:
    name: restaurant
  cloud:
    bootstrap:
      enabled: true
  data:
    mongodb:
      authentication-database: admin
      database: restaurants
      port: 27017
      host: localhost
