server:
  port: 8084

spring:
  application:
    name: restaurant
  cloud:
    bootstrap:
      enabled: true
  data:
    mongodb:
      authentication-database: admin
      database: restaurants
      port: 27017
      host: localhost
