server:
  port: 8761

environment: General Environment

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false

spring:
  application:
    name: discovery
  cloud:
    bootstrap:
      enabled: true
  profiles:
    active: dev