environment: dev

spring:
  application:
    name: product
  cloud:
    bootstrap:
      enabled: true
  kafka:
    bootstrap-servers: PLAINTEXT://kafka:9094

redis.hostname: "productsdb"
redis.port: "6379"

management:
  endpoints:
    enabled: true
    web.exposure.include: beans, loggers, mappings, health, metrics, caches, configprops, sessions

jwt.secretKey: "zlN93cNdQE8hYzSEhLmvl4mGfqcy3wQG2VMHFWpxIx+o2WPkbLkNc5T3xilDSvhC"