environment: dev

spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/userdb
    username: admin
    password: Qwertz123
    driverClassName: org.postgresql.Driver
  application:
    name: user
  cloud:
    bootstrap:
      enabled: true
  kafka:
    bootstrap-servers: PLAINTEXT://localhost:9092



management:
  endpoints:
    enabled: true
    web.exposure.include: beans, loggers, mappings, health, metrics, caches, configprops, sessions

jwt.secretKey: "zlN93cNdQE8hYzSEhLmvl4mGfqcy3wQG2VMHFWpxIx+o2WPkbLkNc5T3xilDSvhC"