server:
  port: 8080

spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/customer
    username: admin
    password: Qwertz123
    driverClassName: org.postgresql.Driver
  application:
    name: customer
  cloud:
    bootstrap:
      enabled: true



logging.level.org.springframework.web: DEBUG

